DELETE FROM mysql.user WHERE User='';

CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASS}';

GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS test;

FLUSH PRIVILEGES;